### PR TITLE
Add many to many relations

### PR DESCRIPTION
**Pull request by brycesch**

### CODE REVIEW

**Comment by cbernaut** [comment]
Is there any plan to include this PR? It would be extremely helpful!!

**Comment by clado** [comment]
@cbernaut I don't believe @brycesch is continuing work on the project, but I plan on picking up where he left off. `has_and_belongs_to_many` is definitely on the list! (Although `belongs_to_many` may take priority.) I don't have a time estimate at the moment, but I'll look into it. :)

**Comment by brycesch** [comment]
@cbernaut @clado I'd be more than willing to continue to work on this pr and this project as a whole. I just never finished this particular pr because my need for it was removed. I don't have a particular time frame for when I could work on this right now, but I'm definitely willing to help out answering any questions and doing code review.

**Comment by brycesch** [comment]
@lukeludwig would you give me collaborator status on this repo so I can continue to help maintain it.

**Comment by clado** [comment]
@brycesch Whatever you have time for would be awesome! Thanks Bryce. :)

**Pull request closed without merging**
